import { writeFile, kebab } from './writer.js';

export function generateAgent(root:string,name:string,type='custom'){
 const id=kebab(name); const role=type; const agent={id,name,role,description:`${name} generated agent`,system_prompt:`You are ${name}. Follow HORUS.md and verify work.`,model_route:'balanced',tools:['read_file','git_status'],mcp_tools:[],memory_scope:'project',permissions:['read-only'],max_runtime:1800,max_tokens:8000,max_cost:1,output_schema:{type:'object'},verification_policy:'tests must pass',handoff_policy:'handoff to reviewer for risky edits',escalation_policy:'ask human for destructive actions'};
 writeFile(root,`src/agents/${id}.ts`,`export const ${camel(id)}Agent = ${JSON.stringify(agent,null,2)} as const;\n`);
 writeFile(root,`tests/${id}.agent.test.ts`,`import test from 'node:test'; import assert from 'node:assert/strict'; import { ${camel(id)}Agent } from '../src/agents/${id}.ts';\ntest('${id} agent schema basics',()=>{ assert.equal(${camel(id)}Agent.id,'${id}'); assert.ok(${camel(id)}Agent.tools.length>0); });\n`);
 writeFile(root,`docs/agents/${id}.md`,`# ${name}\n\nRole: ${role}\n\nExample: run task with agent \`${id}\`.\n`); return agent;
}
export function generateTask(root:string,name:string){const id=kebab(name); const task={id,title:name,description:`${name} generated task`,assigned_agent:'default-agent',dependencies:[],input_schema:{type:'object'},output_schema:{type:'object'},allowed_tools:['read_file'],required_files:[],acceptance_criteria:['structured output','verification passes'],verification_commands:['pnpm test'],retry_policy:'retry once after failure analysis',timeout:1800,budget:1,risk_level:'low'}; writeFile(root,`src/tasks/${id}.ts`,`export const ${camel(id)}Task = ${JSON.stringify(task,null,2)} as const;\nexport async function run${pascal(id)}(input: unknown){ return { task: ${camel(id)}Task.id, input, status: 'planned' }; }\n`); writeFile(root,`tests/${id}.task.test.ts`,`import test from 'node:test'; import assert from 'node:assert/strict'; import { run${pascal(id)} } from '../src/tasks/${id}.ts';\ntest('${id} task runs', async()=>{ const r=await run${pascal(id)}({}); assert.equal(r.status,'planned'); });\n`); writeFile(root,`docs/tasks/${id}.md`,`# ${name}\n\nAcceptance criteria:\n- structured output\n- verification passes\n`); return task;}
export function generateTool(root:string,name:string,category='custom'){const id=kebab(name); const fn=camel(id); const spec={name:id,description:`${name} generated ${category} tool`,input_schema:{type:'object',properties:{dryRun:{type:'boolean'}}},output_schema:{type:'object'},safety_level:'low',permissions_required:['read-only'],timeout:30,dry_run_supported:true,audit_log_enabled:true,retry_policy:'none',error_codes:['VALIDATION_ERROR','EXECUTION_ERROR']}; writeFile(root,`src/tools/${id}.ts`,`import { z } from 'zod';\nexport const ${pascal(id)}Input = z.object({ dryRun: z.boolean().default(true) });\nexport type ${pascal(id)}Result = { ok: boolean; dryRun: boolean };\nexport const ${fn}Spec = ${JSON.stringify(spec,null,2)} as const;\nexport async function ${fn}(input: z.input<typeof ${pascal(id)}Input>): Promise<${pascal(id)}Result>{ const parsed=${pascal(id)}Input.parse(input); return { ok:true, dryRun: parsed.dryRun }; }\n`); writeFile(root,`tests/${id}.tool.test.ts`,`import test from 'node:test'; import assert from 'node:assert/strict'; import { ${fn} } from '../src/tools/${id}.ts';\ntest('${id} tool dry-runs', async()=>{ const r=await ${fn}({}); assert.equal(r.ok,true); });\n`); writeFile(root,`docs/tools/${id}.md`,`# ${name}\n\nSafety: low\nPermissions: read-only\nExample: call \`${fn}({ dryRun: true })\`.\n`); return spec;}
function camel(s:string){return s.replace(/-([a-z])/g,(_,c)=>c.toUpperCase())} function pascal(s:string){const c=camel(s); return c[0].toUpperCase()+c.slice(1)}
