from __future__ import annotations
from pathlib import Path

TEMPLATES = ["coding-agent","research-agent","browser-agent","discord-agent","telegram-agent","devops-agent","repo-auditor","multi-agent-software-team","mcp-native-agent","serverless-agent","personal-assistant-agent","data-pipeline-agent","full-horus-stack"]

def init_project(name: str, template: str = "coding-agent") -> Path:
    if template not in TEMPLATES:
        raise ValueError(f"unknown template {template}")
    root = Path(name)
    for d in ["agents","skills","memory","tools","mcp","docs","tests","examples",".github/workflows"]:
        (root/d).mkdir(parents=True, exist_ok=True)
    (root/"horus.yaml").write_text("models:\n  default: openrouter:anthropic/claude-sonnet-4.5\nagents:\n  max_concurrent: 60\n", encoding="utf-8")
    (root/"README.md").write_text(f"# {name}\n\nGenerated by Horus by Aporia using template `{template}`.\n", encoding="utf-8")
    (root/".env.example").write_text("OPENROUTER_API_KEY=\n", encoding="utf-8")
    (root/"SECURITY.md").write_text("# Security\n\nReview permissions before enabling automation.\n", encoding="utf-8")
    (root/"CONTRIBUTING.md").write_text("# Contributing\n", encoding="utf-8")
    (root/"Dockerfile").write_text("FROM python:3.11-slim\nWORKDIR /app\nCOPY . .\n", encoding="utf-8")
    return root
